### ISSUE TITLE
We are done testing

### ISSUE THREAD

**Issue by Goldenlion5648** [SCCapstone/GreedyGuppyGames#252]
No issue, just wanted to let you guys know we are done testing. Good luck with the rest of the semester!

**Comment by unit220** [comment]
Thanks, we're lookin forward to being able to see you project too. Good luck!

**Comment by Goldenlion5648** [comment]
Our apologies, I said we were done, but we saw that we are recommended to have "a dozen" (I think it was changed from before), so we will be adding a few more bugs
