### ISSUE TITLE
Pressing escape with question mark menu open opens menu

### ISSUE THREAD

**Issue by Goldenlion5648** [SCCapstone/GreedyGuppyGames#257]
When I clicked the "?", this screen came up:
![image](https://user-images.githubusercontent.com/32916571/115174875-1142dd80-a098-11eb-89a4-d1a671f6f7bd.png)

Then after pressing escape once, this menu opened:
![image](https://user-images.githubusercontent.com/32916571/115174913-1ef86300-a098-11eb-968c-12f2cd5ca57a.png)

I would expect escape to just close the "?" menu, not open the pause menu

**Comment by SllimRevilo** [comment]
we wanted this interaction to occur so we will not change it
