### ISSUE TITLE
Buttons stay highlighted when user clicks and holds, then tabs out

### ISSUE THREAD

**Issue by Goldenlion5648** [SCCapstone/GreedyGuppyGames#260]
I was able to get all of the buttons ("?", play, and settings) to be the dark highlight color when I clicked and held, then tabbed out and back into the game.
![image](https://user-images.githubusercontent.com/32916571/115175846-ca55e780-a099-11eb-95f2-a5798673d9ac.png)

**Comment by SllimRevilo** [comment]
This is most likely a Unity specific issue since we are using default unity button functionality, therefore we will not attempt to fix it.
